# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('burst', models.IntegerField(default=5)),
                ('probability', models.FloatField(default=0.07)),
                ('binding_word', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerbot.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='intermediate',
            name='sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerbot.Sticker'),
        ),
        migrations.AddField(
            model_name='chat',
            name='stickers',
            field=models.ManyToManyField(through='stickerbot.Intermediate', to='stickerbot.Sticker'),
        ),
    ]
