# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerbot', '0002_auto_20160908_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='binding_word',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='word',
            field=models.TextField(default=None, null=True),
        ),
    ]
