# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerbot', '0003_auto_20160908_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='binding_word',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='word',
            field=models.TextField(blank=True, default=''),
        ),
    ]
